const dict = {
  'align-content': { alias: 'ac', type: 'string' },
  'align-items': { alias: 'ai', type: 'string' },
  'align-self': { alias: 'asf', type: 'string' },
  all: { alias: 'a', type: 'string' },
  animation: { alias: 'anim', type: 'string' },
  'animation-delay': { alias: 'animdel', type: 'string' },
  'animation-direction': { alias: 'animdir', type: 'string' },
  'animation-duration': { alias: 'animdur', type: 'string' },
  'animation-fill-mode': { alias: 'animfm', type: 'string' },
  'animation-iteration-count': { alias: 'animic', type: 'string' },
  'animation-name': { alias: 'animn', type: 'string' },
  'animation-play-state': { alias: 'animps', type: 'string' },
  'animation-timing-function': { alias: 'animtf', type: 'string' },
  appearance: { alias: 'ap', type: 'string' },
  'backface-visibility': { alias: 'bfv', type: 'string' },
  background: { alias: 'bg', type: 'string' },
  'background-attachment': { alias: 'bga', type: 'string' },
  'background-blend-mode': { alias: 'bgbm', type: 'string' },
  'background-break': { alias: 'bgbk', type: 'string' },
  'background-clip': { alias: 'bgcp', type: 'string' },
  'background-color': { alias: 'bgc', type: 'string' },
  'background-image': { alias: 'bgi', type: 'string' },
  'background-origin': { alias: 'bgo', type: 'string' },
  'background-position': { alias: 'bgp', type: 'string' },
  'background-position-x': { alias: 'bgpx', type: 'string' },
  'background-position-y': { alias: 'bgpy', type: 'string' },
  'background-repeat': { alias: 'bgr', type: 'string' },
  'background-size': { alias: 'bgsz', type: 'string' },
  border: { alias: 'bd', type: 'string' },
  'border-bottom': { alias: 'bdb', type: 'string' },
  'border-bottom-color': { alias: 'bdbc', type: 'string' },
  'border-bottom-image': { alias: 'bdbi', type: 'string' },
  'border-bottom-left-image': { alias: 'bdbli', type: 'string' },
  'border-bottom-left-radius': { alias: 'bdblrs', type: 'string' },
  'border-bottom-right-image': { alias: 'bdbri', type: 'string' },
  'border-bottom-right-radius': { alias: 'bdbrrs', type: 'string' },
  'border-bottom-style': { alias: 'bdbs', type: 'string' },
  'border-bottom-width': { alias: 'bdbw', type: 'string' },
  'border-break': { alias: 'bdbk', type: 'string' },
  'border-collapse': { alias: 'bdcl', type: 'string' },
  'border-corner-image': { alias: 'bdci', type: 'string' },
  'border-color': { alias: 'bdc', type: 'string' },
  'border-fit': { alias: 'bdf', type: 'string' },
  'border-image': { alias: 'bdi', type: 'string' },
  'border-image-outset': { alias: 'bdio', type: 'string' },
  'border-image-repeat': { alias: 'bdir', type: 'string' },
  'border-image-slice': { alias: 'bdisl', type: 'string' },
  'border-image-source': { alias: 'bdiso', type: 'string' },
  'border-image-width': { alias: 'bdiw', type: 'string' },
  'border-left': { alias: 'bdl', type: 'string' },
  'border-left-color': { alias: 'bdlc', type: 'string' },
  'border-left-image': { alias: 'bdli', type: 'string' },
  'border-left-style': { alias: 'bdls', type: 'string' },
  'border-left-width': { alias: 'bdlw', type: 'string' },
  'border-length': { alias: 'bdlen', type: 'string' },
  'border-radius': { alias: 'bdrs', transformer: 'pixel', type: 'string' },
  'border-right': { alias: 'bdr', type: 'string' },
  'border-right-color': { alias: 'bdrc', type: 'string' },
  'border-right-image': { alias: 'bdri', type: 'string' },
  'border-right-style': { alias: 'bdrst', type: 'string' },
  'border-right-width': { alias: 'bdrw', type: 'string' },
  'border-spacing': { alias: 'bdsp', type: 'string' },
  'border-style': { alias: 'bds', type: 'string' },
  'border-top': { alias: 'bdt', type: 'string' },
  'border-top-color': { alias: 'bdtc', type: 'string' },
  'border-top-image': { alias: 'bdti', type: 'string' },
  'border-top-left-image': { alias: 'bdtli', type: 'string' },
  'border-top-left-radius': { alias: 'bdtlrs', type: 'string' },
  'border-top-right-image': { alias: 'bdtri', type: 'string' },
  'border-top-right-radius': { alias: 'bdtrrs', type: 'string' },
  'border-top-style': { alias: 'bdts', type: 'string' },
  'border-top-width': { alias: 'bdtw', type: 'string' },
  'border-width': { alias: 'bdw', transformer: 'pixel', type: 'string' },
  bottom: { alias: 'b', transformer: 'pixel', type: ['number', 'string'] },
  'box-decoration-break': { alias: 'bxdb', type: 'string' },
  'box-shadow': { alias: 'bxsh', type: 'string' },
  'box-sizing': { alias: 'bxsz', type: 'string' },
  'break-after': { type: 'string' },
  'break-before': { type: 'string' },
  'break-inside': { type: 'string' },
  'caption-side': { alias: 'cps', type: 'string' },
  'caret-color': { type: 'string' },
  clear: { alias: 'cl', type: 'string' },
  clip: { alias: 'cp', type: 'string' },
  color: { alias: 'c', type: 'string' },
  'column-count': { alias: 'colmc', type: 'string' },
  'column-fill': { alias: 'colmf', type: 'string' },
  'column-gap': { alias: 'colmg', type: 'string' },
  'column-rule': { alias: 'colmr', type: 'string' },
  'column-rule-color': { alias: 'colmrc', type: 'string' },
  'column-rule-style': { alias: 'colmrs', type: 'string' },
  'column-rule-width': { alias: 'colmrw', type: 'string' },
  'column-span': { alias: 'colms', type: 'string' },
  'column-width': { alias: 'colmw', type: 'string' },
  columns: { alias: 'colm', type: 'string' },
  content: { alias: 'cnt', type: 'string' },
  'counter-increment': { alias: 'coi', type: 'string' },
  'counter-reset': { alias: 'cor', type: 'string' },
  cursor: { alias: 'cur', type: 'string' },
  direction: { type: 'string' },
  display: { alias: 'd', type: 'string' },
  'empty-cells': { alias: 'ec', type: 'string' },
  fill: { alias: 'fil', type: 'string' },
  filter: { alias: 'f', type: 'string' },
  flex: { alias: 'fx', type: 'string' },
  'flex-basis': { alias: 'fxb', transformer: 'width', type: 'string' },
  'flex-direction': { alias: 'fxd', type: 'string' },
  'flex-flow': { alias: 'fxf', type: 'string' },
  'flex-grow': { alias: 'fxg', type: 'string' },
  'flex-shrink': { alias: 'fxs', type: 'string' },
  'flex-wrap': { alias: 'fxw', type: 'string' },
  float: { alias: 'fl', type: 'string' },
  font: { type: 'string' },
  'font-display': { alias: 'fd', type: 'string' },
  'font-effect': { alias: 'fef', type: 'string' },
  'font-emphasize': { alias: 'fem', type: 'string' },
  'font-emphasize-position': { alias: 'femp', type: 'string' },
  'font-emphasize-style': { alias: 'fems', type: 'string' },
  'font-family': { alias: 'ff', type: 'string' },
  'font-feature-settings': { alias: 'ffs', type: 'string' },
  'font-kerning': { alias: 'fk', type: 'string' },
  'font-size': {
    alias: 'fz',
    scale: 'fontSizes',
    transformer: 'fontSize',
    type: ['number', 'string'],
  },
  'font-size-adjust': { alias: 'fsza', type: 'string' },
  'font-smoothing': { alias: 'fsm', type: 'string' },
  'font-stretch': { alias: 'fst', type: 'string' },
  'font-style': { alias: 'fs', type: 'string' },
  'font-variant': { alias: 'fv', type: 'string' },
  'font-variant-caps': { alias: 'fvc', type: 'string' },
  'font-variant-east-asian': { alias: 'fvea', type: 'string' },
  'font-variant-ligatures': { alias: 'fvl', type: 'string' },
  'font-variant-numeric': { alias: 'fvn', type: 'string' },
  'font-variant-position': { alias: 'fvp', type: 'string' },
  'font-variation-settings': { alias: 'fvs', type: 'string' },
  'font-weight': { alias: 'fw', type: ['number', 'string'] },
  grid: { alias: 'gd', type: 'string' },
  'grid-area': { alias: 'gda', type: 'string', process: false },
  'grid-auto-columns': { alias: 'gdac', type: 'string' },
  'grid-auto-flow': { alias: 'gdaf', type: 'string' },
  'grid-auto-rows': { alias: 'gdar', type: 'string' },
  'grid-column': { alias: 'gdc', type: 'string', process: false },
  'grid-column-end': { alias: 'gdce', type: 'string' },
  'grid-column-gap': { alias: 'gdcg', type: 'string', scale: 'space', transformer: 'pixel' },
  'grid-column-start': { alias: 'gdcs', type: 'string' },
  'grid-gap': { alias: 'gdg', type: 'string', scale: 'space', transformer: 'pixel' },
  'grid-row': { alias: 'gdr', type: 'string', process: false },
  'grid-row-end': { alias: 'gdre', type: 'string' },
  'grid-row-gap': { alias: 'gdrg', type: 'string', scale: 'space', transformer: 'pixel' },
  'grid-row-start': { alias: 'gdrs', type: 'string' },
  'grid-template': { alias: 'gdt', type: 'string' },
  'grid-template-areas': { alias: 'gdta', type: 'string' },
  'grid-template-columns': { alias: 'gdtc', type: 'string' },
  'grid-template-rows': { alias: 'gdtr', type: 'string' },
  height: { alias: 'h', transformer: 'pixel', type: ['number', 'string'] },
  hyphens: { alias: 'hphs', type: 'string' },
  isolation: { type: 'string' },
  'justify-content': { alias: 'jc', type: 'string' },
  'justify-items': { alias: 'ji', type: 'string' },
  'justify-self': { alias: 'js', type: 'string' },
  left: { alias: 'l', transformer: 'pixel', type: ['number', 'string'] },
  'letter-spacing': { alias: 'lts', transformer: 'pixel', type: ['number', 'string'] },
  'line-break': { alias: 'lb', type: ['number', 'string'] },
  'line-height': { alias: 'lh', type: ['number', 'string'] },
  'list-style': { alias: 'lis', type: 'string' },
  'list-style-image': { alias: 'lisi', type: 'string' },
  'list-style-position': { alias: 'lisp', type: 'string' },
  'list-style-type': { alias: 'list', type: 'string' },
  margin: { alias: 'm', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'margin-bottom': {
    alias: 'mb',
    scale: 'space',
    transformer: 'space',
    type: ['number', 'string'],
  },
  'margin-left': { alias: 'ml', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'margin-right': { alias: 'mr', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'margin-top': { alias: 'mt', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'margin-x': {
    alias: 'mx',
    transformer: 'pixel',
    type: ['number', 'string'],
    compose: ['marginLeft', 'marginRight'],
  },
  'margin-y': {
    alias: 'my',
    transformer: 'pixel',
    type: ['number', 'string'],
    compose: ['marginTop', 'marginBottom'],
  },
  mask: { type: 'string' },
  'mask-type': { type: 'string' },
  'max-height': { alias: 'mah', transformer: 'pixel', type: ['number', 'string'] },
  'max-resolution': { alias: 'mar', type: 'string' },
  'max-width': { alias: 'maw', transformer: 'pixel', type: ['number', 'string'] },
  'min-height': { alias: 'mih', transformer: 'pixel', type: ['number', 'string'] },
  'min-resolution': { alias: 'mir', type: 'string' },
  'min-width': { alias: 'miw', transformer: 'pixel', type: ['number', 'string'] },
  'mix-blend-mode': { alias: 'mbm', type: 'string' },
  'object-fit': { alias: 'of', type: 'string' },
  'object-position': { alias: 'obp', type: 'string' },
  opacity: { alias: 'op', type: ['number', 'string'] },
  order: { alias: 'ord', type: 'string' },
  orientation: { alias: 'ori', type: 'string' },
  orphans: { alias: 'orp', type: 'string' },
  outline: { alias: 'ol', type: 'string' },
  'outline-color': { alias: 'olc', type: 'string' },
  'outline-offset': { alias: 'olo', type: 'string' },
  'outline-style': { alias: 'ols', type: 'string' },
  'outline-width|thin|medium|thick': { alias: 'olw', type: 'string' },
  overflow: { alias: 'ov', type: 'string' },
  'overflow-style': { alias: 'ovs', type: 'string' },
  'overflow-wrap': { type: 'string' },
  'overflow-x': { alias: 'ovx', type: 'string' },
  'overflow-y': { alias: 'ovy', type: 'string' },
  padding: { alias: 'p', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'padding-bottom': {
    alias: 'pb',
    scale: 'space',
    transformer: 'space',
    type: ['number', 'string'],
  },
  'padding-left': { alias: 'pl', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'padding-right': {
    alias: 'pr',
    scale: 'space',
    transformer: 'space',
    type: ['number', 'string'],
  },
  'padding-top': { alias: 'pt', scale: 'space', transformer: 'space', type: ['number', 'string'] },
  'padding-x': {
    alias: 'px',
    transformer: 'pixel',
    type: ['number', 'string'],
    compose: ['paddingLeft', 'paddingRight'],
  },
  'padding-y': {
    alias: 'py',
    transformer: 'pixel',
    type: ['number', 'string'],
    compose: ['paddingTop', 'paddingBottom'],
  },
  'page-break-after': { alias: 'pgba', type: 'string' },
  'page-break-before': { alias: 'pgbb', type: 'string' },
  'page-break-inside': { alias: 'pgbi', type: 'string' },
  perspective: { alias: 'pspc', type: ['number', 'string'] },
  'perspective-origin': { alias: 'pspco', type: ['number', 'string'] },
  'pointer-events': { alias: 'pe', type: 'string' },
  position: { alias: 'pos', type: 'string' },
  quotes: { type: 'string' },
  ratio: { type: ['number', 'string'] },
  'ratio-padding': { type: ['number', 'string'] },
  resize: { alias: 'rsz', type: 'string' },
  right: { alias: 'r', transformer: 'pixel', type: ['number', 'string'] },
  'scroll-behavior': { type: 'string' },
  'size-height': { type: 'string' },
  'size-width': { type: 'string' },
  'tab-size': { type: 'string' },
  'table-layout': { alias: 'tbl', type: 'string' },
  'text-align': { alias: 'ta', type: 'string' },
  'text-align-last': { alias: 'tal', type: 'string' },
  'text-combine-upright': { alias: 'tcu', type: 'string' },
  'text-decoration': { alias: 'td', type: 'string' },
  'text-decoration-color': { alias: 'tdc', type: 'string' },
  'text-decoration-line': { alias: 'tdl', type: 'string' },
  'text-decoration-style': { alias: 'tds', type: 'string' },
  'text-decoration-thickness': { alias: 'tdth', type: 'string' },
  'text-emphasis': { alias: 'te', type: 'string' },
  'text-height': { alias: 'th', type: 'string' },
  'text-indent': { alias: 'ti', type: ['number', 'string'] },
  'text-justify': { alias: 'tj', type: 'string' },
  'text-orientation': { alias: 'tori', type: 'string' },
  'text-outline': { alias: 'to', type: 'string' },
  'text-overflow': { alias: 'tov', type: 'string' },
  'text-replace': { alias: 'tr', type: 'string' },
  'text-shadow': { alias: 'tsh', type: 'string' },
  'text-transform': { alias: 'tt', type: 'string' },
  'text-underline-position': { alias: 'tup', type: 'string' },
  'text-wrap': { alias: 'tw', type: 'string' },
  top: { alias: 't', transformer: 'pixel', type: ['number', 'string'] },
  transform: { alias: 'trf', type: 'string' },
  'transform-origin': { alias: 'trfo', type: 'string' },
  'transform-style': { alias: 'trfs', type: 'string' },
  transition: { alias: 'trs', type: 'string' },
  'transition-delay': { alias: 'trsde', type: 'string' },
  'transition-duration': { alias: 'trsdu', type: 'string' },
  'transition-property': { alias: 'trsp', type: 'string' },
  'transition-timing-function': { alias: 'trstf', type: 'string' },
  'unicode-bidi': { alias: 'ub', type: 'string' },
  'user-select': { alias: 'us', type: 'string' },
  'vertical-align': { alias: 'va', type: 'string' },
  visibility: { alias: 'v', type: 'string' },
  'white-space': { alias: 'whs', type: 'string' },
  'white-space-collapse': { alias: 'whsc', type: 'string' },
  widows: { alias: 'wid', type: 'string' },
  width: { alias: 'w', transformer: 'width', type: ['number', 'string'] },
  'word-break': { alias: 'wob', type: 'string' },
  'word-spacing': { alias: 'wos', type: 'string' },
  'word-wrap': { alias: 'wow', type: 'string' },
  'writing-mode': { alias: 'wm', type: 'string' },
  'z-index': { alias: 'z', type: 'number' },
  zoom: { alias: 'zom', type: 'string' },
};

export const hashPropsWithAliases = Object.keys(dict).reduce((acc, name) => {
  const propValue = { ...dict[name], name };
  acc[name] = propValue;
  if (propValue.alias) acc[propValue.alias] = propValue;
  return acc;
}, {});

export default dict;
