export type AvailableProps = {
  margin?: number | string;
  'margin-top'?: number | string;
  'margin-right'?: number | string;
  'margin-bottom'?: number | string;
  'margin-left'?: number | string;
  padding?: number | string;
  'padding-top'?: number | string;
  'padding-right'?: number | string;
  'padding-bottom'?: number | string;
  'padding-left'?: number | string;
  font?: string;
  'font-size'?: number | string;
  'font-variant'?: string;
  color?: string;
  cursor?: string;
  transition?: string;
  'transition-delay'?: string;
  'transition-duration'?: string;
  'transition-property'?: string;
  'transition-timing-function'?: string;
  'object-fit'?: string;
  'object-position'?: string;
  'font-family'?: string;
  'text-align'?: string;
  'text-transform'?: string;
  'word-spacing'?: string;
  'word-break'?: string;
  'white-space'?: string;
  'text-indent'?: number | string;
  'mix-blend-mode'?: string;
  'line-height'?: number | string;
  'font-weight'?: number | string;
  'font-style'?: string;
  'text-decoration'?: string;
  'text-decoration-line'?: string;
  'text-decoration-color'?: string;
  'text-decoration-style'?: string;
  'text-decoration-thickness'?: string;
  'letter-spacing'?: number | string;
  display?: string;
  width?: number | string;
  'max-width'?: number | string;
  'min-width'?: number | string;
  height?: number | string;
  'max-height'?: number | string;
  'min-height'?: number | string;
  'user-select'?: string;
  'vertical-align'?: string;
  'align-items'?: string;
  'align-content'?: string;
  'justify-items'?: string;
  'justify-content'?: string;
  'flex-wrap'?: string;
  'flex-grow'?: string;
  'flex-shrink'?: string;
  'flex-basis'?: string;
  'flex-direction'?: string;
  flex?: string;
  'justify-self'?: string;
  'align-self'?: string;
  order?: string;
  'grid-gap'?: string;
  'grid-column-gap'?: string;
  'grid-row-gap'?: string;
  'grid-column'?: string;
  'grid-row'?: string;
  'grid-auto-flow'?: string;
  'grid-auto-columns'?: string;
  'grid-auto-rows'?: string;
  'grid-template-columns'?: string;
  'grid-template-rows'?: string;
  'grid-template-areas'?: string;
  'grid-template'?: string;
  'grid-area'?: string;
  border?: string;
  'border-width'?: string;
  'border-style'?: string;
  'border-top'?: string;
  'border-right'?: string;
  'border-bottom'?: string;
  'border-left'?: string;
  'border-color'?: string;
  'border-radius'?: string;
  'box-shadow'?: string;
  'box-sizing'?: string;
  opacity?: number | string;
  outline?: string;
  overflow?: string;
  background?: string;
  'background-color'?: string;
  'background-image'?: string;
  'background-position'?: string;
  'background-repeat'?: string;
  'background-size'?: string;
  'background-blend-mode'?: string;
  'background-attachment'?: string;
  filter?: string;
  position?: string;
  'z-index'?: number;
  top?: number | string;
  right?: number | string;
  bottom?: number | string;
  left?: number | string;
  transform?: string;
  'transform-origin'?: string;
  'transform-style'?: string;
  'list-style'?: string;
  'list-style-type'?: string;
  'list-style-image'?: string;
  'list-style-position'?: string;
  'padding-x'?: number | string;
  'padding-y'?: number | string;
  'margin-x'?: number | string;
  'margin-y'?: number | string;
  animation?: string;
  'animation-delay'?: string;
  'animation-direction'?: string;
  'animation-duration'?: string;
  'animation-fill-mode'?: string;
  'animation-iteration-count'?: string;
  'animation-name'?: string;
  'animation-play-state'?: string;
  'animation-timing-function'?: string;
  appearance?: string;
  'border-bottom-color'?: string;
  'border-bottom-left-radius'?: string;
  'border-bottom-right-radius'?: string;
  'border-bottom-style'?: string;
  'border-bottom-width'?: string;
  'border-collapse'?: string;
  'border-image'?: string;
  'border-left-color'?: string;
  'border-left-style'?: string;
  'border-left-width'?: string;
  'border-right-color'?: string;
  'border-right-style'?: string;
  'border-right-width'?: string;
  'border-spacing'?: string;
  'border-top-color'?: string;
  'border-top-left-radius'?: string;
  'border-top-right-radius'?: string;
  'border-top-style'?: string;
  'border-top-width'?: string;
  'backface-visibility'?: string;
  'background-clip'?: string;
  'background-origin'?: string;
  'background-position-x'?: string;
  'background-position-y'?: string;
  clear?: string;
  content?: string;
  'counter-increment'?: string;
  columns?: string;
  'column-count'?: string;
  'column-fill'?: string;
  'column-gap'?: string;
  'column-rule'?: string;
  'column-rule-color'?: string;
  'column-rule-style'?: string;
  'column-rule-width'?: string;
  'column-span'?: string;
  'column-width'?: string;
  'counter-reset'?: string;
  clip?: string;
  'caption-side'?: string;
  'empty-cells'?: string;
  float?: string;
  'font-stretch'?: string;
  'font-variation-settings'?: string;
  'flex-flow'?: string;
  'font-size-adjust'?: string;
  grid?: string;
  'grid-column-start'?: string;
  'grid-column-end'?: string;
  'grid-row-start'?: string;
  'grid-row-end'?: string;
  'outline-color'?: string;
  'outline-offset'?: string;
  'outline-style'?: string;
  'outline-width'?: string;
  orphans?: string;
  'overflow-x'?: string;
  'overflow-y'?: string;
  'page-break-after'?: string;
  'page-break-before'?: string;
  'page-break-inside'?: string;
  perspective?: number | string;
  resize?: string;
  'text-align-last'?: string;
  'table-layout'?: string;
  'text-emphasis'?: string;
  'text-justify'?: string;
  'text-overflow'?: string;
  'text-shadow'?: string;
  visibility?: string;
  widows?: string;
  'writing-mode'?: string;
  'word-wrap'?: string;
  zoom?: string;
  fill?: string;
};

export type Aliases = {
  m?: number | string;
  mt?: number | string;
  mr?: number | string;
  mb?: number | string;
  ml?: number | string;
  p?: number | string;
  pt?: number | string;
  pr?: number | string;
  pb?: number | string;
  pl?: number | string;
  fz?: number | string;
  fv?: string;
  c?: string;
  cur?: string;
  trs?: string;
  trsde?: string;
  trsdu?: string;
  trsp?: string;
  trstf?: string;
  of?: string;
  obp?: string;
  ff?: string;
  ta?: string;
  tt?: string;
  wos?: string;
  wob?: string;
  whs?: string;
  ti?: number | string;
  mbm?: string;
  lh?: number | string;
  fw?: number | string;
  fs?: string;
  td?: string;
  tdl?: string;
  tdc?: string;
  tds?: string;
  tdth?: string;
  lts?: number | string;
  d?: string;
  w?: number | string;
  maw?: number | string;
  miw?: number | string;
  h?: number | string;
  mah?: number | string;
  mih?: number | string;
  us?: string;
  va?: string;
  ai?: string;
  ac?: string;
  ji?: string;
  jc?: string;
  fxw?: string;
  fxg?: string;
  fxs?: string;
  fxb?: string;
  fxd?: string;
  fx?: string;
  js?: string;
  asf?: string;
  ord?: string;
  bd?: string;
  bdw?: string;
  bds?: string;
  bdt?: string;
  bdr?: string;
  bdb?: string;
  bdl?: string;
  bdc?: string;
  bdrs?: string;
  bxsh?: string;
  bxsz?: string;
  op?: number | string;
  ol?: string;
  ov?: string;
  bg?: string;
  bgc?: string;
  bgi?: string;
  bgp?: string;
  bgr?: string;
  bgsz?: string;
  bbm?: string;
  bga?: string;
  f?: string;
  pos?: string;
  z?: number;
  t?: number | string;
  r?: number | string;
  b?: number | string;
  l?: number | string;
  trf?: string;
  trfo?: string;
  trfs?: string;
  lis?: string;
  list?: string;
  lisi?: string;
  lisp?: string;
  px?: number | string;
  py?: number | string;
  mx?: number | string;
  my?: number | string;
  anim?: string;
  animdel?: string;
  animdir?: string;
  animdur?: string;
  animfm?: string;
  animic?: string;
  animn?: string;
  animps?: string;
  animtf?: string;
  ap?: string;
  bdbc?: string;
  bdblrs?: string;
  bdbrrs?: string;
  bdbs?: string;
  bdbw?: string;
  bdcl?: string;
  bdi?: string;
  bdlc?: string;
  bdls?: string;
  bdlw?: string;
  bdrc?: string;
  bdrst?: string;
  bdrw?: string;
  bdsp?: string;
  bdtc?: string;
  bdtlrs?: string;
  bdtrrs?: string;
  bdts?: string;
  bdtw?: string;
  bfv?: string;
  bgcp?: string;
  bgo?: string;
  bgpx?: string;
  bgpy?: string;
  cl?: string;
  cnt?: string;
  coi?: string;
  colm?: string;
  colmc?: string;
  colmf?: string;
  colmg?: string;
  colmr?: string;
  colmrc?: string;
  colmrs?: string;
  colmrw?: string;
  colms?: string;
  colmw?: string;
  cor?: string;
  cp?: string;
  cps?: string;
  ec?: string;
  fl?: string;
  fst?: string;
  fvs?: string;
  fxf?: string;
  fsza?: string;
  gd?: string;
  gcs?: string;
  gce?: string;
  grs?: string;
  gre?: string;
  olc?: string;
  olo?: string;
  ols?: string;
  olw?: string;
  orp?: string;
  ovx?: string;
  ovy?: string;
  pgba?: string;
  pgbb?: string;
  pgbi?: string;
  pspc?: number | string;
  rsz?: string;
  tal?: string;
  tbl?: string;
  te?: string;
  tj?: string;
  tov?: string;
  tsh?: string;
  v?: string;
  wid?: string;
  wm?: string;
  wow?: string;
  zom?: string;
  fil?: string;
};
